/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Category = IDL.Variant({
  'dessert' : IDL.Null,
  'healthy' : IDL.Null,
  'sushi' : IDL.Null,
  'indian' : IDL.Null,
  'pizza' : IDL.Null,
  'burger' : IDL.Null,
});
export const FoodItemInput = IDL.Record({
  'name' : IDL.Text,
  'description' : IDL.Text,
  'restaurantId' : IDL.Nat,
  'imageUrl' : IDL.Text,
  'category' : Category,
  'price' : IDL.Nat,
});
export const RestaurantInput = IDL.Record({
  'name' : IDL.Text,
  'deliveryTime' : IDL.Nat,
  'imageUrl' : IDL.Text,
  'cuisine' : IDL.Text,
  'rating' : IDL.Float64,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const FoodItem = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'restaurantId' : IDL.Nat,
  'imageUrl' : IDL.Text,
  'category' : Category,
  'price' : IDL.Nat,
});
export const Restaurant = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'deliveryTime' : IDL.Nat,
  'imageUrl' : IDL.Text,
  'cuisine' : IDL.Text,
  'rating' : IDL.Float64,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
  'address' : IDL.Text,
  'phone' : IDL.Text,
});
export const CartItem = IDL.Record({
  'foodItemId' : IDL.Nat,
  'quantity' : IDL.Nat,
});
export const Time = IDL.Int;
export const Order = IDL.Record({
  'id' : IDL.Nat,
  'status' : IDL.Variant({
    'cancelled' : IDL.Null,
    'pending' : IDL.Null,
    'delivered' : IDL.Null,
  }),
  'total' : IDL.Nat,
  'userId' : IDL.Principal,
  'timestamp' : Time,
  'items' : IDL.Vec(
    IDL.Record({ 'foodItemId' : IDL.Nat, 'quantity' : IDL.Nat })
  ),
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addFoodItem' : IDL.Func([FoodItemInput], [IDL.Nat], []),
  'addRestaurant' : IDL.Func([RestaurantInput], [IDL.Nat], []),
  'addToCart' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'clearCart' : IDL.Func([], [], []),
  'getAllFoodItems' : IDL.Func([], [IDL.Vec(FoodItem)], ['query']),
  'getAllRestaurants' : IDL.Func([], [IDL.Vec(Restaurant)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCart' : IDL.Func([], [IDL.Vec(CartItem)], ['query']),
  'getFoodItemsByCategory' : IDL.Func(
      [Category],
      [IDL.Vec(FoodItem)],
      ['query'],
    ),
  'getFoodItemsByRestaurant' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(FoodItem)],
      ['query'],
    ),
  'getUserOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'placeOrder' : IDL.Func([], [IDL.Nat], []),
  'removeFoodItem' : IDL.Func([IDL.Nat], [], []),
  'removeFromCart' : IDL.Func([IDL.Nat], [], []),
  'removeRestaurant' : IDL.Func([IDL.Nat], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'seedSampleData' : IDL.Func([], [], []),
  'updateFoodItem' : IDL.Func([IDL.Nat, FoodItemInput], [], []),
  'updateRestaurant' : IDL.Func([IDL.Nat, RestaurantInput], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Category = IDL.Variant({
    'dessert' : IDL.Null,
    'healthy' : IDL.Null,
    'sushi' : IDL.Null,
    'indian' : IDL.Null,
    'pizza' : IDL.Null,
    'burger' : IDL.Null,
  });
  const FoodItemInput = IDL.Record({
    'name' : IDL.Text,
    'description' : IDL.Text,
    'restaurantId' : IDL.Nat,
    'imageUrl' : IDL.Text,
    'category' : Category,
    'price' : IDL.Nat,
  });
  const RestaurantInput = IDL.Record({
    'name' : IDL.Text,
    'deliveryTime' : IDL.Nat,
    'imageUrl' : IDL.Text,
    'cuisine' : IDL.Text,
    'rating' : IDL.Float64,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const FoodItem = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'restaurantId' : IDL.Nat,
    'imageUrl' : IDL.Text,
    'category' : Category,
    'price' : IDL.Nat,
  });
  const Restaurant = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'deliveryTime' : IDL.Nat,
    'imageUrl' : IDL.Text,
    'cuisine' : IDL.Text,
    'rating' : IDL.Float64,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'address' : IDL.Text,
    'phone' : IDL.Text,
  });
  const CartItem = IDL.Record({ 'foodItemId' : IDL.Nat, 'quantity' : IDL.Nat });
  const Time = IDL.Int;
  const Order = IDL.Record({
    'id' : IDL.Nat,
    'status' : IDL.Variant({
      'cancelled' : IDL.Null,
      'pending' : IDL.Null,
      'delivered' : IDL.Null,
    }),
    'total' : IDL.Nat,
    'userId' : IDL.Principal,
    'timestamp' : Time,
    'items' : IDL.Vec(
      IDL.Record({ 'foodItemId' : IDL.Nat, 'quantity' : IDL.Nat })
    ),
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addFoodItem' : IDL.Func([FoodItemInput], [IDL.Nat], []),
    'addRestaurant' : IDL.Func([RestaurantInput], [IDL.Nat], []),
    'addToCart' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'clearCart' : IDL.Func([], [], []),
    'getAllFoodItems' : IDL.Func([], [IDL.Vec(FoodItem)], ['query']),
    'getAllRestaurants' : IDL.Func([], [IDL.Vec(Restaurant)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCart' : IDL.Func([], [IDL.Vec(CartItem)], ['query']),
    'getFoodItemsByCategory' : IDL.Func(
        [Category],
        [IDL.Vec(FoodItem)],
        ['query'],
      ),
    'getFoodItemsByRestaurant' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(FoodItem)],
        ['query'],
      ),
    'getUserOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'placeOrder' : IDL.Func([], [IDL.Nat], []),
    'removeFoodItem' : IDL.Func([IDL.Nat], [], []),
    'removeFromCart' : IDL.Func([IDL.Nat], [], []),
    'removeRestaurant' : IDL.Func([IDL.Nat], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'seedSampleData' : IDL.Func([], [], []),
    'updateFoodItem' : IDL.Func([IDL.Nat, FoodItemInput], [], []),
    'updateRestaurant' : IDL.Func([IDL.Nat, RestaurantInput], [], []),
  });
};

export const init = ({ IDL }) => { return []; };