/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface CartItem { 'foodItemId' : bigint, 'quantity' : bigint }
export type Category = { 'dessert' : null } |
  { 'healthy' : null } |
  { 'sushi' : null } |
  { 'indian' : null } |
  { 'pizza' : null } |
  { 'burger' : null };
export interface FoodItem {
  'id' : bigint,
  'name' : string,
  'description' : string,
  'restaurantId' : bigint,
  'imageUrl' : string,
  'category' : Category,
  'price' : bigint,
}
export interface FoodItemInput {
  'name' : string,
  'description' : string,
  'restaurantId' : bigint,
  'imageUrl' : string,
  'category' : Category,
  'price' : bigint,
}
export interface Order {
  'id' : bigint,
  'status' : { 'cancelled' : null } |
    { 'pending' : null } |
    { 'delivered' : null },
  'total' : bigint,
  'userId' : Principal,
  'timestamp' : Time,
  'items' : Array<{ 'foodItemId' : bigint, 'quantity' : bigint }>,
}
export interface Restaurant {
  'id' : bigint,
  'name' : string,
  'deliveryTime' : bigint,
  'imageUrl' : string,
  'cuisine' : string,
  'rating' : number,
}
export interface RestaurantInput {
  'name' : string,
  'deliveryTime' : bigint,
  'imageUrl' : string,
  'cuisine' : string,
  'rating' : number,
}
export type Time = bigint;
export interface UserProfile {
  'name' : string,
  'email' : string,
  'address' : string,
  'phone' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addFoodItem' : ActorMethod<[FoodItemInput], bigint>,
  'addRestaurant' : ActorMethod<[RestaurantInput], bigint>,
  'addToCart' : ActorMethod<[bigint, bigint], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'clearCart' : ActorMethod<[], undefined>,
  'getAllFoodItems' : ActorMethod<[], Array<FoodItem>>,
  'getAllRestaurants' : ActorMethod<[], Array<Restaurant>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCart' : ActorMethod<[], Array<CartItem>>,
  'getFoodItemsByCategory' : ActorMethod<[Category], Array<FoodItem>>,
  'getFoodItemsByRestaurant' : ActorMethod<[bigint], Array<FoodItem>>,
  'getUserOrders' : ActorMethod<[], Array<Order>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'placeOrder' : ActorMethod<[], bigint>,
  'removeFoodItem' : ActorMethod<[bigint], undefined>,
  'removeFromCart' : ActorMethod<[bigint], undefined>,
  'removeRestaurant' : ActorMethod<[bigint], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'seedSampleData' : ActorMethod<[], undefined>,
  'updateFoodItem' : ActorMethod<[bigint, FoodItemInput], undefined>,
  'updateRestaurant' : ActorMethod<[bigint, RestaurantInput], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];